DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS requests;
DROP TABLE IF EXISTS complication;
DROP TABLE IF EXISTS complication_events;
DROP TABLE IF EXISTS followers;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name  VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    CONSTRAINT PK_users_id PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS categories
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name_category VARCHAR(200) NOT NULL,
    CONSTRAINT PK_categories_id PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    annotation         VARCHAR(2000)            NOT NULL,
    category_id        BIGINT,
    created_on         TIMESTAMP WITH TIME ZONE NOT NULL,
    description        VARCHAR(7000),
    event_date         TIMESTAMP WITH TIME ZONE NOT NULL,
    initiator_id       BIGINT,
    is_paid            BOOLEAN                  NOT NULL,
    title              VARCHAR(120)             NOT NULL,
    participant_limit  INTEGER                  NOT NULL,
    locat_lat          DOUBLE PRECISION,
    locat_lon          DOUBLE PRECISION,
    request_moderation BOOLEAN DEFAULT True,
    published_on       TIMESTAMP WITH TIME ZONE,
    state              VARCHAR(50),
    confirmed_request  INTEGER,
    CONSTRAINT PK_events_id PRIMARY KEY (id),
    CONSTRAINT FK_events_category_id FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE,
    CONSTRAINT FK_events_users_id FOREIGN KEY (initiator_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    event_id     BIGINT,
    requester_id BIGINT,
    created_at   TIMESTAMP NOT NULL,
    status       VARCHAR(15),
    CONSTRAINT PK_request_id PRIMARY KEY (id),
    CONSTRAINT FK_requests_events_id FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
    CONSTRAINT FK_requests_users_id FOREIGN KEY (requester_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS complication
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    is_pinned BOOLEAN,
    title     VARCHAR(255),
    CONSTRAINT PK_complication_id PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS complication_events
(
    complication_id BIGINT,
    events_id       BIGINT,
    CONSTRAINT PK_complication_events PRIMARY KEY (complication_id, events_id),
    CONSTRAINT FK_complication_events_complication_id FOREIGN KEY (complication_id) REFERENCES complication (id) ON DELETE CASCADE,
    CONSTRAINT FK_complication_events_events_id FOREIGN KEY (events_id) REFERENCES events (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS followers
(
    user_id     BIGINT NOT NULL,
    follower_id BIGINT NOT NULL,
    CONSTRAINT PK_followers PRIMARY KEY (user_id, follower_id),
    CONSTRAINT FK_user_id_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT FK_follower_id_user_id FOREIGN KEY (follower_id) REFERENCES users (id) ON DELETE CASCADE
);

