version: '3.1'
services:
  statistic-prog:
    build: ./stats-service/stat-server
    image: statistic-image
    container_name: statistic-prog-container
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:shareit;MODE=PostgreSQL
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVER_PORT=9090

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    ports:
      - "7654:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=statistic

  ewm-service:
    build: ./main-service
    image: main-image
    container_name: main-prog-container
    depends_on:
      - ewm-db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:shareit;MODE=PostgreSQL
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVER_PORT=8080

  ewm-db:
    image: postgres:14-alpine
    container_name: main-db-container
    ports:
      - "7651:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=main